# Like the review, grab the place_id and go!

In [ ]:
# https://www.google.com/maps/place/?q=place_id:ChIJZ9pzJ8UPdkgRn46ont0RtTY

# Load Prediction.csv

In [2]:
import pandas as pd
from LondonEmotions.data import clean_data

In [8]:
df = pd.read_csv("../raw_data/prediction.csv")
# df = df.review.astype(str)
df.head()

place_id        lat       lng                                             review
0  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Nice budget hotel....room is clean and well ma...
1  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  This hotel is well managed with great staff on...
2  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  10 our of 10 lovely service, clean and homely....
3  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Very Dirty, carpet never been cleaned, Curry s...
4  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Even 1 star is too much for this terrible hote...

In [9]:
# rename it to Text
df.rename(columns={'review': 'Text'}, inplace=True)
df['Text'] = df['Text'].astype(str)
df.head()

place_id        lat       lng                                               Text
0  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Nice budget hotel....room is clean and well ma...
1  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  This hotel is well managed with great staff on...
2  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  10 our of 10 lovely service, clean and homely....
3  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Very Dirty, carpet never been cleaned, Curry s...
4  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Even 1 star is too much for this terrible hote...

# Cleaning

In [10]:
# df['clean_text'] = df['Text'].str.lower() #astype didn't work?
clean_data(df)
df.head()

place_id        lat       lng                                               Text                                         clean_text  \
0  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Nice budget hotel....room is clean and well ma...  nice budget hotelroom is clean and well mainta...   
1  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  This hotel is well managed with great staff on...  this hotel is well managed with great staff on...   
2  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  10 our of 10 lovely service, clean and homely....  our of lovely service clean and homely with lo...   
3  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Very Dirty, carpet never been cleaned, Curry s...  very dirty carpet never been cleaned curry sta...   
4  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Even 1 star is too much for this terrible hote...  even star is too much for this terrible hotel ...   

                                      tokenized_text  
0  [nice, budget, hotelroom, is, clean, and, well...  
1  [this, hotel, is, well, managed, with, great, ...  
2  [our, of, lovely, service, clean, and, homely,...  
3  [very, dirty, carpet, never, been, cleaned, cu...  
4  [even, star, is, too, much, for, this, terribl...

# Manual labelling

In [11]:
# joy, sad, angry, worry, neutral
# slice it now or later
# df = df[500:600]
# text = df['Text']
# len(df)

In [12]:
# load full text
count = 1
for i in df['Text'].iloc[500:600]:
    print(f"{count}: {i}")
    print('---------------------------')
    count += 1

1: I think this hotel is good but only shared spaces which look newly refurbished.

However some if the rooms and carpets are stained and should be replaced.

The shower screen had limescale and stagnant water which was about disgusting.

The water drainage in the shower waa very slow.

This is a place you stay asclast resort.
---------------------------
2: Room and hotel were clean and fit for purpose. Room was just a bit small. But diagonally opposite the museum, so perfectly situated. Also walking distance to Royal Albert Hall for if you book to see a show in the evening. And near South Kensington Tube station. So very good for convenience sake.
---------------------------
3: Avoid avoid.

Tiny rooms and not very clean, got given a room in a basement with a tiny window. Terrible customer service from reception task.

Parking was advertised as free but bad to pay over £60 for my 2 day stay nearby.

Many better hotels nearby to chose from work free parking also
-----------------------

In [15]:
# labelling
answer = ['worry', 'joy', 'sad', 'joy', 'sad', 'joy', 'joy', 'joy', 'joy', 'joy',
        'neutral', 'joy', 'neutral', 'joy', 'joy', 'joy', 'joy', 'worry', 'worry', 'joy',
        'sad', 'anger', 'worry', 'joy', 'joy', 'worry', 'neutral', 'joy', 'anger', 'worry',
        'joy', 'sad', 'joy', 'sad', 'neutral', 'joy', 'joy', 'joy', 'worry', 'joy',
        'joy', 'joy', 'anger', 'joy', 'joy', 'worry', 'worry', 'joy', 'joy', 'joy',
        'neutral', 'neutral', 'neutral', 'neutral', 'neutral', 'joy', 'joy', 'worry', 'neutral', 'neutral',
        'sad', 'sad', 'anger', 'anger', 'anger', 'neutral', 'joy', 'worry', 'sad', 'joy',
        'joy', 'joy', 'joy', 'joy', 'joy', 'joy', 'worry', 'sad', 'worry', 'neutral',
        'anger', 'anger', 'joy', 'anger', 'joy', 'joy', 'anger', 'worry', 'joy', 'joy',
        'joy', 'joy', 'joy', 'anger', 'neutral', 'joy', 'worry', 'joy', 'sad', 'sad']

In [16]:
# check it's 100
len(answer)

100

In [19]:
# bang the labels to new column 'emotion'
alan_df = df[500:600]
alan_df['emotion'] = answer

c:\users\al\.venvs\lewagon\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [21]:
alan_df['emotion'].value_counts()

joy        49
worry      15
neutral    14
sad        11
anger      11
Name: emotion, dtype: int64

In [14]:
df['place_id'][513]

'ChIJZ9pzJ8UPdkgRn46ont0RtTY'

In [23]:
alan_df.head()

place_id        lat       lng                                               Text                                         clean_text  \
500  ChIJKSDtn10FdkgRPbUAQKJlQ7U  51.495128 -0.179319  I think this hotel is good but only shared spa...  i think this hotel is good but only shared spa...   
501  ChIJKSDtn10FdkgRPbUAQKJlQ7U  51.495128 -0.179319  Room and hotel were clean and fit for purpose....  room and hotel were clean and fit for purpose ...   
502  ChIJKSDtn10FdkgRPbUAQKJlQ7U  51.495128 -0.179319  Avoid avoid.\r\n\r\nTiny rooms and not very cl...  avoid avoid tiny room and not very clean got g...   
503  ChIJKSDtn10FdkgRPbUAQKJlQ7U  51.495128 -0.179319  Hidden gem\r\n\r\nWestminster Building + Decor...  hidden gem westminster building decorating ltd...   
504  ChIJKSDtn10FdkgRPbUAQKJlQ7U  51.495128 -0.179319  I am a frequent flyer for business and had to ...  i am a frequent flyer for business and had to ...   

                                        tokenized_text emotion  
500  [think, this, hotel, is, good, but, only, shar...   worry  
501  [room, and, hotel, were, clean, and, fit, for,...     joy  
502  [avoid, avoid, tiny, room, and, not, very, cle...     sad  
503  [hidden, gem, westminster, building, decoratin...     joy  
504  [am, frequent, flyer, for, business, and, had,...     sad

In [22]:
alan_df.to_csv('alan_df.csv', index=False)

In [65]:
alan_df2 = pd.read_csv('alan_df.csv')
alan_df2.head()

place_id        lat       lng                                               Text                                         clean_text  \
0  ChIJKSDtn10FdkgRPbUAQKJlQ7U  51.495128 -0.179319  I think this hotel is good but only shared spa...  i think this hotel is good but only shared spa...   
1  ChIJKSDtn10FdkgRPbUAQKJlQ7U  51.495128 -0.179319  Room and hotel were clean and fit for purpose....  room and hotel were clean and fit for purpose ...   
2  ChIJKSDtn10FdkgRPbUAQKJlQ7U  51.495128 -0.179319  Avoid avoid.\r\n\r\nTiny rooms and not very cl...  avoid avoid tiny room and not very clean got g...   
3  ChIJKSDtn10FdkgRPbUAQKJlQ7U  51.495128 -0.179319  Hidden gem\r\n\r\nWestminster Building + Decor...  hidden gem westminster building decorating ltd...   
4  ChIJKSDtn10FdkgRPbUAQKJlQ7U  51.495128 -0.179319  I am a frequent flyer for business and had to ...  i am a frequent flyer for business and had to ...   

                                      tokenized_text emotion  
0  ['think', 'this', 'hotel', 'is', 'good', 'but'...   worry  
1  ['room', 'and', 'hotel', 'were', 'clean', 'and...     joy  
2  ['avoid', 'avoid', 'tiny', 'room', 'and', 'not...     sad  
3  ['hidden', 'gem', 'westminster', 'building', '...     joy  
4  ['am', 'frequent', 'flyer', 'for', 'business',...     sad

# Apply the model (old)

In [ ]:
! ls ../raw_data

In [ ]:
from tensorflow.keras.models import load_model

In [ ]:
# # model = load_model('./raw_data')
# # model = load_model(os.path.join("../raw_data","saved_model.pd"))
# # model = load_model('gs://wagon-ml-london-emotions/models/emotions/v2/saved_model.pb')
#model = load_model('../raw_data/saved_model.pb')
# #loaded_model = tf.keras.models.load_model('../raw_data')

# model = load_model('../raw_data')
# filepath = '../raw_data'
# # with file_io.FileIO(filepath, mode='r') as f


In [ ]:
# model = load_model('../raw_data')
model = load_model('../raw_data/saved_model.pb')

In [ ]:
model.(df)

# Apply the model new

## Grab and clean data

In [24]:
import pandas as pd
import string
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer
from gensim import utils

import nltk
nltk.download('stopwords')

from LondonEmotions.utils import create_embedding_matrix
from tensorflow.python.lib.io import file_io

In [40]:
review_df = pd.read_csv('../raw_data/prediction.csv')
review_df.rename(columns = {'review': 'Text'}, inplace=True)
review_df['Text'] = review_df['Text'].astype(str)
review_df.head()

place_id        lat       lng                                               Text
0  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Nice budget hotel....room is clean and well ma...
1  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  This hotel is well managed with great staff on...
2  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  10 our of 10 lovely service, clean and homely....
3  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Very Dirty, carpet never been cleaned, Curry s...
4  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Even 1 star is too much for this terrible hote...

In [41]:
clean_data(review_df)
review_df.head()

place_id        lat       lng                                               Text                                         clean_text  \
0  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Nice budget hotel....room is clean and well ma...  nice budget hotelroom is clean and well mainta...   
1  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  This hotel is well managed with great staff on...  this hotel is well managed with great staff on...   
2  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  10 our of 10 lovely service, clean and homely....  our of lovely service clean and homely with lo...   
3  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Very Dirty, carpet never been cleaned, Curry s...  very dirty carpet never been cleaned curry sta...   
4  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Even 1 star is too much for this terrible hote...  even star is too much for this terrible hotel ...   

                                      tokenized_text  
0  [nice, budget, hotelroom, is, clean, and, well...  
1  [this, hotel, is, well, managed, with, great, ...  
2  [our, of, lovely, service, clean, and, homely,...  
3  [very, dirty, carpet, never, been, cleaned, cu...  
4  [even, star, is, too, much, for, this, terribl...

## The model

In [42]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.python.lib.io import file_io
import pickle

In [48]:
num_classes = 5
embed_num_dims = 300
max_seq_len = 300
class_names = ['joy', 'worry', 'anger', 'sad', 'neutral']

reviews = review_df['tokenized_text']

sentences_pred = [[_ for _ in sentence] for sentence in reviews]

texts_pred = [' '.join([x for x in sentence]) for sentence in sentences_pred]

# Tokenize text (convert to integers) (LOAD SAVED TOKNIZER -- CAN ALSO RETRIEVE FROM GCP)
filepath = '../raw_data/tokenizer.pickle'
with file_io.FileIO(filepath, mode='rb') as handle:
    tokenizer = pickle.load(handle)

sequence_pred = tokenizer.texts_to_sequences(texts_pred)

index_of_words = tokenizer.word_index

# vacab size is number of unique words + reserved 0 index for padding
vocab_size = len(index_of_words) + 1

# Padding text sentences
X_pred_pad = pad_sequences(sequence_pred, maxlen = max_seq_len )


In [49]:
X_pred_pad

array([[   0,    0,    0, ...,  197,   84,  537],
       [   0,    0,    0, ..., 3334,  541,  876],
       [   0,    0,    0, ...,  876,   19,   23],
       ...,
       [   0,    0,    0, ..., 8558,  271,  684],
       [   0,    0,    0, ..., 5649,   73, 1052],
       [   0,    0,    0, ...,  749,  294,  211]])

In [ ]:
# Encode target
    encoding = {
    'anger': 0,
    'joy': 1,
    'worry': 2,
    'neutral': 3,
    'sad': 4
    }

In [50]:
from tensorflow.keras.models import load_model
model = load_model('../raw_data/saved_model.pb')
preds = model.predict(X_pred_pad)

In [51]:
print(preds)

[[0.02905648 0.19406627 0.50860006 0.0276215  0.24065568]
 [0.12818776 0.07312929 0.45927614 0.07705467 0.2623521 ]
 [0.05074719 0.5071262  0.15375517 0.19909781 0.08927361]
 ...
 [0.08875266 0.20280546 0.5838012  0.05758075 0.06705988]
 [0.05030318 0.08474547 0.2960779  0.5027143  0.06615911]
 [0.09284611 0.13587722 0.32487068 0.05110097 0.3953051 ]]


In [52]:
preds

array([[0.02905648, 0.19406627, 0.50860006, 0.0276215 , 0.24065568],
       [0.12818776, 0.07312929, 0.45927614, 0.07705467, 0.2623521 ],
       [0.05074719, 0.5071262 , 0.15375517, 0.19909781, 0.08927361],
       ...,
       [0.08875266, 0.20280546, 0.5838012 , 0.05758075, 0.06705988],
       [0.05030318, 0.08474547, 0.2960779 , 0.5027143 , 0.06615911],
       [0.09284611, 0.13587722, 0.32487068, 0.05110097, 0.3953051 ]],
      dtype=float32)

In [53]:
preds_categorical = []
for prediction in preds:
    preds_categorical.append(np.argmax(prediction))

In [54]:
preds_categorical

[2,
 2,
 1,
 1,
 1,
 1,
 4,
 1,
 2,
 2,
 4,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 4,
 2,
 0,
 4,
 2,
 1,
 1,
 1,
 4,
 4,
 1,
 2,
 1,
 2,
 1,
 4,
 0,
 1,
 2,
 1,
 1,
 2,
 4,
 4,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 4,
 3,
 4,
 1,
 0,
 3,
 0,
 3,
 4,
 2,
 1,
 0,
 2,
 2,
 2,
 2,
 1,
 1,
 3,
 2,
 2,
 1,
 2,
 3,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 4,
 2,
 2,
 1,
 2,
 4,
 2,
 3,
 1,
 1,
 4,
 2,
 1,
 1,
 2,
 2,
 3,
 4,
 1,
 4,
 4,
 1,
 2,
 2,
 0,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 4,
 1,
 1,
 2,
 2,
 2,
 3,
 3,
 1,
 2,
 1,
 1,
 1,
 1,
 4,
 3,
 4,
 3,
 1,
 2,
 2,
 2,
 1,
 3,
 3,
 3,
 2,
 1,
 3,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 0,
 3,
 1,
 4,
 1,
 2,
 1,
 3,
 3,
 2,
 3,
 1,
 1,
 1,
 1,
 2,
 4,
 4,
 2,
 2,
 2,
 2,
 3,
 3,
 1,
 4,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 0,
 3,
 1,
 2,
 1,
 2,
 1,
 3,
 2,
 4,
 1,
 4,
 3,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 4,
 2,
 3,
 3,
 1,
 2,
 3,
 1,
 2,
 4,
 2,
 4,
 1,
 1,
 1,
 3,
 2,
 2,
 1,
 3,
 2,
 1,
 1,
 2,


In [56]:
encoding = {0: 'anger', 1: 'joy', 2: 'worry', 3: 'neutral', 4: 'sad'}
pred_series = pd.Series(preds_categorical)
review_predictions = pred_series.map(encoding)
review_predictions.value_counts()

worry      794
joy        749
neutral    214
sad        202
anger       86
dtype: int64

In [58]:
review_df['emotion'] = review_predictions
review_df.head()

place_id        lat       lng                                               Text                                         clean_text  \
0  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Nice budget hotel....room is clean and well ma...  nice budget hotelroom is clean and well mainta...   
1  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  This hotel is well managed with great staff on...  this hotel is well managed with great staff on...   
2  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  10 our of 10 lovely service, clean and homely....  our of lovely service clean and homely with lo...   
3  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Very Dirty, carpet never been cleaned, Curry s...  very dirty carpet never been cleaned curry sta...   
4  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Even 1 star is too much for this terrible hote...  even star is too much for this terrible hotel ...   

                                      tokenized_text emotion  
0  [nice, budget, hotelroom, is, clean, and, well...   worry  
1  [this, hotel, is, well, managed, with, great, ...   worry  
2  [our, of, lovely, service, clean, and, homely,...     joy  
3  [very, dirty, carpet, never, been, cleaned, cu...     joy  
4  [even, star, is, too, much, for, this, terribl...     joy

In [63]:
# manually labeled:
# joy        49
# worry      15
# neutral    14
# sad        11
# anger      11

# what the model predict?
review_df['emotion'][500:600].value_counts()

worry      46
joy        32
neutral    15
sad         4
anger       3
Name: emotion, dtype: int64

# Merge labelled data

In [89]:
# pd.concat([df1, df2])
def merge(df1, df2, df3):
    merged_df = pd.concat([df1, df2, df3])
    return merged_df

In [85]:
df3 = pd.read_csv('../raw_data/label_aude.csv')
df3.head()

place_id        lat       lng                                               Text                                         clean_text  \
0  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586  Absolutely perfect restaurant, in fact it coul...  absolutely perfect restaurant in fact it could...   
1  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586  Finally visited after the closure of Little Ba...  finally visited after the closure of little ba...   
2  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586  Thrilled that this beautiful restaurant has op...  thrilled that this beautiful restaurant ha ope...   
3  ChIJMzzxp6AcdkgRAbgqxgqGStg  51.531084 -0.093748  Warm atmosphere, cosy and relaxing. Great musi...  warm atmosphere cosy and relaxing great music ...   
4  ChIJMzzxp6AcdkgRAbgqxgqGStg  51.531084 -0.093748  Cracking boozer. Five stars all round. Good se...  cracking boozer five star all round good selec...   

                                      tokenized_text emotion emo_manually_added  
0  ['absolutely', 'perfect', 'restaurant', 'in', ...     sad                sad  
1  ['finally', 'visited', 'after', 'the', 'closur...   worry                joy  
2  ['thrilled', 'that', 'this', 'beautiful', 'res...     joy                joy  
3  ['warm', 'atmosphere', 'cosy', 'and', 'relaxin...     joy            neutral  
4  ['cracking', 'boozer', 'five', 'star', 'all', ...   worry                joy

In [86]:
df1 = pd.read_csv('../raw_data/label_aude.csv')[['place_id', 'lat', 'lng', 'emo_manually_added', 'Text']]
df2 = pd.read_csv('../raw_data/label_luke.csv')[['place_id', 'lat', 'lng', 'emotion', 'review']]
df3 = pd.read_csv('../raw_data/label_alan.csv')[['place_id', 'lat', 'lng', 'emotion', 'Text']]

In [88]:
# rankings_pd.rename(columns = {'test':'TEST'}, inplace = True) 
df1.rename(columns = {'emo_manually_added': 'emotion', 'Text': 'review'}, inplace=True)
df3.rename(columns = {'Text': 'review'}, inplace=True)

In [90]:
pred_testset = merge(df1, df2, df3)

In [91]:
#alan_df.to_csv('alan_df.csv', index=False)
pred_testset.to_csv('pred_testset.csv', index=False)

In [123]:
# check it out
dell = pd.read_csv('../raw_data/pred_testset.csv')
dell.head()

place_id        lat       lng  emotion                                             review
0  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586      sad  Absolutely perfect restaurant, in fact it coul...
1  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586      joy  Finally visited after the closure of Little Ba...
2  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586      joy  Thrilled that this beautiful restaurant has op...
3  ChIJMzzxp6AcdkgRAbgqxgqGStg  51.531084 -0.093748  neutral  Warm atmosphere, cosy and relaxing. Great musi...
4  ChIJMzzxp6AcdkgRAbgqxgqGStg  51.531084 -0.093748      joy  Cracking boozer. Five stars all round. Good se...

In [ ]:
    joy_df = data[data['emotion']=='joy'] #updatekey
    joy_df = joy_df.T

In [112]:
joy_df = dell[dell['emotion']=='joy']
joy_df.head()

place_id        lat       lng emotion                                             review
1  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586     joy  Finally visited after the closure of Little Ba...
2  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586     joy  Thrilled that this beautiful restaurant has op...
4  ChIJMzzxp6AcdkgRAbgqxgqGStg  51.531084 -0.093748     joy  Cracking boozer. Five stars all round. Good se...
5  ChIJMzzxp6AcdkgRAbgqxgqGStg  51.531084 -0.093748     joy  place is always busy and rightly so, they’ve g...
6  ChIJMzzxp6AcdkgRAbgqxgqGStg  51.531084 -0.093748     joy  A real gem of a pub, probably my favourite lon...

In [117]:
dell.rename(columns={'lng':'lon'}, inplace=True)
# data = pd.DataFrame([dell['lat'], dell['lon']])
# data.head()
dell = dell.T
dell.head()

0                                                  1                                                  2     \
place_id                        ChIJv29u9WYbdkgRBrykLCrPnQw                        ChIJv29u9WYbdkgRBrykLCrPnQw                        ChIJv29u9WYbdkgRBrykLCrPnQw   
lat                                                 51.5396                                            51.5396                                            51.5396   
lon                                               -0.102586                                          -0.102586                                          -0.102586   
emotion                                                 sad                                                joy                                                joy   
review    Absolutely perfect restaurant, in fact it coul...  Finally visited after the closure of Little Ba...  Thrilled that this beautiful restaurant has op...   

                                                       3                                                  4                                                  5     \
place_id                        ChIJMzzxp6AcdkgRAbgqxgqGStg                        ChIJMzzxp6AcdkgRAbgqxgqGStg                        ChIJMzzxp6AcdkgRAbgqxgqGStg   
lat                                                 51.5311                                            51.5311                                            51.5311   
lon                                              -0.0937482                                         -0.0937482                                         -0.0937482   
emotion                                             neutral                                                joy                                                joy   
review    Warm atmosphere, cosy and relaxing. Great musi...  Cracking boozer. Five stars all round. Good se...  place is always busy and rightly so, they’ve g...   

                                                       6                            7                                                8                                                  9     ...  \
place_id                        ChIJMzzxp6AcdkgRAbgqxgqGStg  ChIJMzzxp6AcdkgRAbgqxgqGStg                      ChIJYVig82YbdkgRi6zgskkA6TM                        ChIJYVig82YbdkgRi6zgskkA6TM  ...   
lat                                                 51.5311                      51.5311                                          51.5397                                            51.5397  ...   
lon                                              -0.0937482                   -0.0937482                                        -0.102337                                          -0.102337  ...   
emotion                                                 joy                          joy                                            worry                                                joy  ...   
review    A real gem of a pub, probably my favourite lon...     Best cask beer in town..  The healthy food surpassed expectations by far.  Great food, really love the flavours that are ...  ...   

                                                       2236                                               2237                                               2238  \
place_id                        ChIJLV9o4dwbdkgRhMIKDC4RWQU                        ChIJLV9o4dwbdkgRhMIKDC4RWQU                        ChIJLV9o4dwbdkgRhMIKDC4RWQU   
lat                                                 51.5903                                            51.5903                                            51.5903   
lon                                               -0.120939                                          -0.120939                                          -0.120939   
emotion                                                 joy                                                joy                                                joy   
review    It's a very nice place. Very large lounge with...  Love

In [122]:
joy_df = dell[dell['emotion']=='joy'] #updatekey
joy_df = joy_df.T

KeyError: 'emotion'

In [115]:
joy_df = dell[dell['emotion']=='joy'] 
joy_df.head()

place_id        lat       lng emotion                                             review
1  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586     joy  Finally visited after the closure of Little Ba...
2  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586     joy  Thrilled that this beautiful restaurant has op...
4  ChIJMzzxp6AcdkgRAbgqxgqGStg  51.531084 -0.093748     joy  Cracking boozer. Five stars all round. Good se...
5  ChIJMzzxp6AcdkgRAbgqxgqGStg  51.531084 -0.093748     joy  place is always busy and rightly so, they’ve g...
6  ChIJMzzxp6AcdkgRAbgqxgqGStg  51.531084 -0.093748     joy  A real gem of a pub, probably my favourite lon...

In [119]:
testit = pd.read_csv('../raw_data/pred_testset.csv')

In [120]:
testit.head()

place_id        lat       lng  emotion                                             review
0  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586      sad  Absolutely perfect restaurant, in fact it coul...
1  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586      joy  Finally visited after the closure of Little Ba...
2  ChIJv29u9WYbdkgRBrykLCrPnQw  51.539604 -0.102586      joy  Thrilled that this beautiful restaurant has op...
3  ChIJMzzxp6AcdkgRAbgqxgqGStg  51.531084 -0.093748  neutral  Warm atmosphere, cosy and relaxing. Great musi...
4  ChIJMzzxp6AcdkgRAbgqxgqGStg  51.531084 -0.093748      joy  Cracking boozer. Five stars all round. Good se...

In [121]:
preview = pd.read_csv('../raw_data/review_predictions.csv')
preview.head()

Unnamed: 0                     place_id        lat       lng                                               Text                                         clean_text  \
0           0  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Nice budget hotel....room is clean and well ma...  nice budget hotelroom clean well maintainedgoo...   
1           1  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  This hotel is well managed with great staff on...  hotel well managed great staff hour reception ...   
2           2  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  10 our of 10 lovely service, clean and homely....  lovely service clean homely lovely resident ne...   
3           3  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Very Dirty, carpet never been cleaned, Curry s...  dirty carpet never cleaned curry stain carpet ...   
4           4  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Even 1 star is too much for this terrible hote...  even star much terrible hotel room dirty clean...   

                                      tokenized_text emotion  
0  ['nice', 'budget', 'hotelroom', 'clean', 'well...   worry  
1  ['hotel', 'well', 'managed', 'great', 'staff',...   worry  
2  ['lovely', 'service', 'clean', 'homely', 'love...     joy  
3  ['dirty', 'carpet', 'never', 'cleaned', 'curry...     joy  
4  ['even', 'star', 'much', 'terrible', 'hotel', ...     joy

# Button

In [ ]:
import pandas as pd
button = pd.read_csv('../raw_data/pred_testset.csv')

In [14]:
button.shape

(2246, 5)

In [15]:
button['emotion'].value_counts()

joy        167
neutral     39
anger       33
sad         29
worry       27
Neutral      1
Joy          1
Sad          1
Anger        1
Name: emotion, dtype: int64

In [10]:
joy_button = button[button['emotion']=='joy']
joy_button['place_id'].value_counts()

ChIJO6vgkWcFdkgRjLCrLkS_3ak    6
ChIJKSDtn10FdkgRPbUAQKJlQ7U    6
ChIJDeqJal4FdkgRkrlDfWtBPNw    5
ChIJQRA31fQPdkgRDa8iiwy-GcI    5
ChIJDeqJal4FdkgRyboPczDa_-8    5
ChIJP0wwqWAFdkgRMuqRLzHiCHM    5
ChIJIXvOu-QbdkgRDj-fpH1C0E8    5
ChIJz1y33_cPdkgRP3ghYOpJYoI    5
ChIJNdTypRWm2EcRGOVqTq72t44    4
ChIJVWd-ULgPdkgR6YP4gY60HQA    4
ChIJvTehVPUPdkgRUieu4YLfcUo    4
ChIJKSMdVEu72EcROnG__fcK31s    4
ChIJXeC1Cl4FdkgRbOWJlFcZHLU    4
ChIJq5YDCh272EcRLYdpEzcbtGw    4
ChIJYVig82YbdkgRi6zgskkA6TM    4
ChIJ78YAFBEcdkgRIwD7e_LGfMY    4
ChIJMzzxp6AcdkgRAbgqxgqGStg    4
ChIJzacQU9cbdkgReQhGeXtnOJo    4
ChIJqVIOIfUPdkgRerErzHPHpkE    4
ChIJ-4kPg4sPdkgRvllCY0z_8bs    4
ChIJdX6YBbik2EcRmqHVqP63Nn0    3
ChIJiwVttYym2EcRUdFHMteOfCo    3
ChIJM6qXlrWk2EcRKcE2DZNpaXE    3
ChIJLW7hTG-u2EcRcBPNakWWbwU    3
ChIJJ-LmW_Sm2EcRAet_3xIEtUw    3
ChIJk4Kflpmm2EcR44Z1_QnyTY8    3
ChIJBeJgcvQbdkgR-bC9Nl8Z6Z4    3
ChIJNT8NrJEPdkgRmyDOqth_efg    3
ChIJp1t__G6l2EcR0e3lX2oGko4    3
ChIJfZ_5N5Sl2EcRMDAdxyEt9RA    3
ChIJZ9pzJ8

In [12]:
#dataframe[column].value_counts().index.tolist()
joyest = joy_button['place_id'].value_counts().index.tolist()[0]

In [13]:
f"https://www.google.com/maps/place/?q=place_id:{joyest}"

'https://www.google.com/maps/place/?q=place_id:ChIJO6vgkWcFdkgRjLCrLkS_3ak'

# Textbox

In [43]:
import pandas as pd
text = 'Hello world, I am feeling great today! The world is wonderful YES!!!'
text_df = {
    'Text': [text]
}
text_df = pd.DataFrame(text_df)
text_df.head()

Text
0  Hello world, I am feeling great today! The wor...

In [44]:
from LondonEmotions.data import clean_data
clean_text = clean_data(text_df)
clean_text

Text                                         clean_text                                     tokenized_text
0  Hello world, I am feeling great today! The wor...  hello world feeling great today world wonderfu...  [hello, world, feeling, great, today, world, w...

In [53]:
text_value = clean_text['tokenized_text']
text_value[0]

['hello', 'world', 'feeling', 'great', 'today', 'world', 'wonderful', 'yes']

In [102]:
# save and load tokenizer: 
#https://stackoverflow.com/questions/45735070/keras-text-preprocessing-saving-tokenizer-object-to-file-for-scoring
#
# GCP path: gs://wagon-ml-london-emotions/models/tokenizer/model_tokenizer
from tensorflow.python.lib.io import file_io
import pickle
# with file_io.FileIO('models_tokenizer_model_tokenizer.pickle', 'rb') as handle:
# #     tokenizer = pickle.load(handle)
# tokenizer = pickle.load('gs://wagon-ml-london-emotions/models/tokenizer/model_tokenizer.pickle')

#local?
# tokenizer = models_tokenizer_model_tokenizer.pickle
with file_io.FileIO('../models_tokenizer_model_tokenizer', 'rb') as handle:
     tokenizer = pickle.load(handle)

In [103]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
max_seq_len = 300
index_of_words = tokenizer.word_index
vocab_size = len(index_of_words) + 1
sequence_text = tokenizer.texts_to_sequences(text_value)
text_pad = pad_sequences(sequence_text, maxlen=max_seq_len)
text_pad

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [104]:
from tensorflow.keras.models import load_model
model = load_model('../raw_data/saved_model.pb')
preds = model.predict(text_pad)

In [105]:
preds

array([[0.04116383, 0.05932348, 0.49449673, 0.21327509, 0.19174081]],
      dtype=float32)

In [106]:
preds.sum()

0.99999994

In [107]:
#str(round(answer, 2))
angry = str(round(preds[0][0]*100,2))
joy = str(round(preds[0][1]*100,2))
worry = str(round(preds[0][2]*100,2))
neutral = str(round(preds[0][3]*100,2))
sad = str(round(preds[0][4]*100,2))

In [108]:
print(f"Joy: {joy}%")
print(f"Worry: {worry}%")
print(f"Sad: {sad}%")
print(f"Neutral: {neutral}%")
print(f"Angry: {angry}%")

Joy: 5.93%
Worry: 49.45%
Sad: 19.17%
Neutral: 21.33%
Angry: 4.12%


In [110]:
x = pd.read_csv("../downloads/predicted_reviews.csv")
x.head()

place_id        lat       lng                                               Text                                         clean_text  \
0  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Nice budget hotel....room is clean and well ma...  nice budget hotelroom is clean and well mainta...   
1  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  This hotel is well managed with great staff on...  this hotel is well managed with great staff on...   
2  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  10 our of 10 lovely service, clean and homely....  our of lovely service clean and homely with lo...   
3  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Very Dirty, carpet never been cleaned, Curry s...  very dirty carpet never been cleaned curry sta...   
4  ChIJiwVttYym2EcRUdFHMteOfCo  51.563524  0.070761  Even 1 star is too much for this terrible hote...  even star is too much for this terrible hotel ...   

                                      tokenized_text emotion manually_added_emotion  joy, sad, worry, anger, neutral  
0  ['nice', 'budget', 'hotelroom', 'is', 'clean',...   worry                    NaN                              NaN  
1  ['this', 'hotel', 'is', 'well', 'managed', 'wi...   worry                    NaN                              NaN  
2  ['our', 'of', 'lovely', 'service', 'clean', 'a...     joy                    NaN                              NaN  
3  ['very', 'dirty', 'carpet', 'never', 'been', '...     joy                    NaN                              NaN  
4  ['even', 'star', 'is', 'too', 'much', 'for', '...     joy                    NaN                              NaN